# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('day_idx', models.IntegerField(verbose_name='day_number')),
                ('general_eval', models.IntegerField(verbose_name='general_self_evaluation(1-4)')),
                ('body_temp', models.DecimalField(decimal_places=1, max_digits=20, max_length=11, verbose_name='body_temperature')),
                ('sleep_time', models.DecimalField(decimal_places=1, max_digits=20, max_length=11, verbose_name='sleep_time')),
                ('health_score', models.IntegerField(null=True, verbose_name='health_score')),
                ('blog', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
                'db_table': 'day_stat',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(verbose_name='s_id')),
                ('name', models.CharField(max_length=100, verbose_name='symptom')),
                ('owner', models.ManyToManyField(to='data.DayStat')),
            ],
            options={
                'db_table': 'symptoms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='daystat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User'),
        ),
    ]
