# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='owner',
        ),
        migrations.AddField(
            model_name='daystat',
            name='symptoms',
            field=models.ManyToManyField(to='data.Symptom'),
        ),
    ]
